# Sheldon configuration file

shell = "zsh"

[plugins]

[plugins.fzf-bin]
github = "junegunn/fzf"
tag = "latest"
apply = ["PATH"]

[plugins.fzf]
github = "junegunn/fzf"
apply = ["PATH", "source"]
use = ["shell/*.zsh"]

[plugins.zsh-notify]
github = "marzocchi/zsh-notify"
apply = ["source"]

[plugins.k]
github = "supercrabtree/k"
apply = ["source"]

[plugins.zsh-bd]
github = "Tarrasch/zsh-bd"
apply = ["source"]

[plugins.cd-gitroot]
github = "mollifier/cd-gitroot"
apply = ["source"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["source"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["source"]

[plugins.hub-zsh-completion]
github = "glidenote/hub-zsh-completion"
apply = ["fpath"]

[plugins.zsh-curl-completion]
github = "Valodim/zsh-curl-completion"
apply = ["fpath"]

[plugins.cf-zsh-autocomplete-plugin]
github = "dannyzen/cf-zsh-autocomplete-plugin"
apply = ["fpath"]

[plugins.nssh]
github = "fujiwara/nssh"
tag = "latest"
apply = ["PATH"]
use = ["nssh"]

[plugins.ghr]
github = "tcnksm/ghr"
tag = "latest"
apply = ["PATH"]

[plugins.httpstat]
github = "reorx/httpstat"
apply = ["PATH"]
use = ["httpstat.py"]

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["source"]
use = ["init.sh"]

[plugins.zsh-dircolors-solarized]
github = "joel-porquet/zsh-dircolors-solarized"
apply = ["source"]

# Command plugins with more complex setups can be installed manually
# and referenced here as local plugins if needed

[templates]
PATH = 'export PATH="{{ dir }}:$PATH"'
